{
 "title": "📊 Обзор Apache (трафик, IP, страницы)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "📊 Всего запросов",
   "type": "stat",
   "description": "Общее количество HTTP-запросов за выбранный период",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"apache_access\"}[$__range]))"
    }
   ]
  },
  {
   "title": "🔥 Ошибки сервера (5xx)",
   "type": "stat",
   "description": "Доля ошибок 5xx от общего числа запросов за выбранный период.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time({job=\"apache_access\"} |~ \"5[0-9]{2}\" [$__range])) / sum(count_over_time({job=\"apache_access\"}[$__range]))) * 100"
    }
   ]
  },
  {
   "title": "⚠️ Ошибки клиента (4xx)",
   "type": "stat",
   "description": "Доля ошибок 4xx от общего числа запросов за выбранный период",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time({job=\"apache_access\"} |~ \"4[0-9]{2}\" [$__range])) / sum(count_over_time({job=\"apache_access\"}[$__range]))) * 100"
    }
   ]
  },
  {
   "title": "📊 Количество ответов по HTTP-статусам",
   "type": "table",
   "description": "Абсолютное число ответов сервера с каждым HTTP-статусом за выбранный период. Сумма всех столбцов равна общему числу запросов (Total Requests)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"apache_access\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests per second by site",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (site) (rate({job=\"apache_access\"}[5m]))",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "🌐 Топ-10 IP-адресов (за 24 часа)",
   "type": "bargauge",
   "description": "IP-адреса с наибольшим количеством запросов за последние сутки. Помогает выявить подозрительную активность, ботов или источники высокой нагрузки",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,\r\n  sum by (ip) (\r\n    count_over_time(\r\n      {job=\"apache_access\"} \r\n      | regexp `^(?P<ip>\\S+)` \r\n      | label_format ip=`{{.ip}}`\r\n      [24h]\r\n    )\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "🔝 Самые популярные страницы (за 24 часа)",
   "type": "bargauge",
   "description": "Количество запросов к каждой странице за последние сутки. Помогает оценить нагрузку и выявить подозрительную активность (например, перебор страниц).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,\r\n  sum by (path) (\r\n    count_over_time(\r\n      {job=\"apache_access\"} \r\n      | regexp `\"(?P<method>\\S+) (?P<path>/[^/?#]*)` \r\n      | label_format path=`{{.path}}`\r\n      [24h]\r\n    )\r\n  )\r\n)"
    }
   ]
  }
 ]
}