{
 "title": "🌐 Трафик по сайтам",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "📊 Общий трафик",
   "type": "stat",
   "description": "Суммарный объём данных, переданных посетителям за выбранный период. Большие значения могут указывать на высокую нагрузку или скачивание файлов.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  sum_over_time(\r\n    {job=\"apache_access\"} \r\n    | regexp `\\s(?P<bytes>\\d+)(?:\\s|-)` \r\n    | unwrap bytes\r\n    [$__range]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "📈 Запросы в секунду (по сайтам)",
   "type": "timeseries",
   "description": "Скорость поступления запросов на каждый сайт. Показывает активность посетителей в реальном времени. Резкие скачки – повод проверить трафик",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (site) (rate({job=\"apache_access\"}[5m]))",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "📦 Трафик в секунду (по сайтам)",
   "type": "timeseries",
   "description": "Скорость передачи данных по каждому сайту. Позволяет оценить, какой сайт генерирует наибольший объём трафика",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (site) (\r\n  rate(\r\n    {job=\"apache_access\"} \r\n    | regexp `\\s(?P<bytes>\\d+)` \r\n    | unwrap bytes\r\n    [5m]\r\n  )\r\n)",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "📋 Сводка по сайтам",
   "type": "table",
   "description": "Таблица с итоговыми показателями за выбранный период: количество запросов, переданный объём, количество ошибок 4xx (клиентские) и 5xx (серверные). Помогает быстро выявить проблемные сайты",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (site) (count_over_time({job=\"apache_access\"}[$__range]))"
    },
    {
     "expr": "sum by (site) (sum_over_time({job=\"apache_access\"} | unwrap bytes | __error__=\"\" [$__range]))"
    },
    {
     "expr": "sum by (site) (count_over_time({job=\"apache_access\"} |~ \"4[0-9]{2}\" [$__range]))"
    },
    {
     "expr": "sum by (site) (count_over_time({job=\"apache_access\"} |~ \"5[0-9]{2}\" [$__range]))"
    }
   ]
  }
 ]
}